version: '3.9'

services:
  postgres:
    image: 'postgres:14-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data

  # 1. connect / sys as sysdba
  # 2. password: oracle
  #  create user gregor identified by gregor;
  #  grant connect to gregor;
  #  grant all privileges to gregor;
  oracle:
    image: container-registry.oracle.com/database/free:latest
    ports:
      - '1521:1521'
    volumes:
      - .:/duo
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=0000

volumes:
  postgres-data:
  oracle-backup: